name: Run Photoniq FaaS CLI

on: [workflow_dispatch]

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Set up and print repository path
        run: |
          REPO_PATH=functions/$(echo ${GITHUB_REPOSITORY##*/})
          echo "REPO_PATH=$REPO_PATH" >> $GITHUB_ENV
          echo "Repository will be checked out to: $REPO_PATH"

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_PATH }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install Photoniq FaaS CLI via npm
        run: npm install -g @macrometa/faas

      - name: Verify CLI installation
        run: faas --version  
      
      - name: List directory to verify does functions folder exist
        run: ls -l 

      - name: List directory to verify content of functions folder
        run: ls -l functions
      
      - name: Run CLI and print output
        run: |
          echo "Running Photoniq FaaS CLI..."
          export API_URL="${{ secrets.API_URL }}"
          export API_KEY="${{ secrets.API_KEY }}"
          faas remote deploy $(echo ${GITHUB_REPOSITORY##*/})

      # - name: Run CLI and print output
      #   run: |
      #     echo "Running Photoniq FaaS CLI..."
      #     export API_URL="${{ secrets.API_URL }}"
      #     export API_KEY="${{ secrets.API_KEY }}"
      #     faas remote list